export const HANDLE_APPLICATION_STEP = "HANDLE_APPLICATION_STEP";
export const RESET_APPLICATION_STEP = "RESET_APPLICATION_STEP";
// Application Details input handling
export const HANDLE_APPLICATION_DETAILS = "HANDLE_APPLICATION_DETAILS";
export const HANDLE_APPLICATION_TYPE = "HANDLE_APPLICATION_TYPE";
export const HANDLE_BUSINESS_OWNERSHIP = "HANDLE_BUSINESS_OWNERSHIP";
export const HANDLE_BUSINESS_OWNER_ADDRESS = "HANDLE_BUSINESS_OWNER_ADDRESS";
export const HANDLE_BUSINESS_CURRENT = "HANDLE_BUSINESS_CURRENT";
export const HANDLE_BUSINESS_ADDRESS = "HANDLE_BUSINESS_ADDRESS";
export const HANDLE_CREDIT_CARD_ACCEPTANCE = "HANDLE_CREDIT_CARD_ACCEPTANCE";
export const HANDLE_CASH_ADVANCE = "HANDLE_CASH_ADVANCE";
export const HANDLE_BUSINESS_LOCATION = "HANDLE_BUSINESS_LOCATION";
export const HANDLE_APPLICATION_SIGNATURE = "HANDLE_APPLICATION_SIGNATURE";
export const APPLICATION_SUBMIT_SUCCESS = "APPLICATION_SUBMIT_SUCCESS";
export const APPLICATION_SUBMIT_ERROR = "APPLICATION_SUBMIT_ERROR";
// Application Save
export const APPLICATION_SAVE_RESPONSE = "APPLICATION_SAVE_RESPONSE";
export const APPLICATION_SAVE_ERROR = "APPLICATION_SAVE_ERROR";
// application list
export const APPLICATION_LIST = "APPLICATION_LIST";
export const APPLICATION_LIST_ERROR = "APPLICATION_LIST_ERROR";
// Get Application Details
export const APPLICATION_DETAILS_RESPONSE = "APPLICATION_DETAILS_RESPONSE";
export const APPLICATION_DETAILS_ERROR = "APPLICATION_DETAILS_ERROR";
export const REPLACE_APPLICATION_DETAILS = "REPLACE_APPLICATION_DETAILS";
// Reset Application
export const RESET_APPLICATION_DETAILS = "RESET_APPLICATION_DETAILS";
// Auth Actions Types
export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";
export const RECEIVE_USER_DATA_ERROR = "RECEIVE_USER_DATA_ERROR";
export const HANDLE_LOGIN_SUCCESS = "HANDLE_LOGIN_SUCCESS";
export const HANDLE_LOGIN_ERROR = "HANDLE_LOGIN_ERROR";
export const HANDLE_EMAIL_SUCCESS = "HANDLE_EMAIL_SUCCESS";
export const HANDLE_EMAIL_ERROR = "HANDLE_EMAIL_ERROR";
export const HANDLE_EMAIL_CODE_ERROR = "HANDLE_EMAIL_CODE_ERROR";
export const RESET_MESSAGE = "RESET_MESSAGE";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";
export const GET_PLANS_SUCCESS = "GET_PLANS_SUCCESS";
export const GET_PLANS_ERROR = "GET_PLANS_ERROR";
export const HANDLE_REGISTER_ERROR = "HANDLE_REGISTER_ERROR";
export const HANDLE_IS_USER_AUTHENTICATED = "HANDLE_IS_USER_AUTHENTICATED";
export const HANDLE_IS_VERIFICATION_CODE_SENT =
  "HANDLE_IS_VERIFICATION_CODE_SENT";
export const HANDLE_IS_AUTH_FETCHING = "HANDLE_IS_AUTH_FETCHING";
// Forgot Password
export const RECEIVE_PASSWORD_RESET_TOKEN = "RECEIVE_PASSWORD_RESET_TOKEN";
export const RECEIVE_PASSWORD_RESET_TOKEN_ERROR =
  "RECEIVE_PASSWORD_RESET_TOKEN_ERROR";
export const RESET_PASSWORD_TOKEN = "RESET_PASSWORD_TOKEN";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const FORGOT_PASSWORD_TOGGLE = "FORGOT_PASSWORD_TOGGLE";
// Verification
export const HANDLE_IS_USER_VERIFIED = "HANDLE_IS_USER_VERIFIED";
export const SEND_VERIFICATION_SMS_SUCCESS = "SEND_VERIFICATION_SMS_SUCCESS";
export const SEND_VERIFICATION_SMS_FAILURE = "SEND_VERIFICATION_SMS_FAILURE";
export const AUTH_CODE_RESPONSE = "AUTH_CODE_RESPONSE";
//Outlets
export const RECEIVE_USER_OUTLETS = "RECEIVE_USER_OUTLETS";
export const UPDATE_OUTLET = "UPDATE_OUTLET";

export const GET_SINGLE_OUTLET = "GET_SINGLE_OUTLET";
//Events
export const RECEIVE_USER_EVENTS = "RECEIVE_USER_EVENTS";
