export const HANDLE_APPLICATION_STEP = "HANDLE_APPLICATION_STEP";
export const RESET_APPLICATION_STEP = "RESET_APPLICATION_STEP";
// Auth Actions Types
export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";
export const RECEIVE_USER_DATA_ERROR = "RECEIVE_USER_DATA_ERROR";
export const HANDLE_LOGIN_REQUEST = "HANDLE_LOGIN_REQUEST";
export const HANDLE_LOGIN_SUCCESS = "HANDLE_LOGIN_SUCCESS";
export const HANDLE_LOGIN_ERROR = "HANDLE_LOGIN_ERROR";
export const HANDLE_EMAIL_SUCCESS = "HANDLE_EMAIL_SUCCESS";
export const HANDLE_EMAIL_ERROR = "HANDLE_EMAIL_ERROR";
export const HANDLE_EMAIL_CODE_ERROR = "HANDLE_EMAIL_CODE_ERROR";
export const RESET_MESSAGE = "RESET_MESSAGE";
export const RESET_DISCOUNT_MESSAGE = "RESET_DISCOUNT_MESSAGE";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";
export const GET_PLANS_SUCCESS = "GET_PLANS_SUCCESS";
export const GET_PLANS_ERROR = "GET_PLANS_ERROR";
export const GET_DISCOUNT_VALUE_SUCCESS = "GET_DISCOUNT_VALUE_SUCCESS";
export const GET_DISCOUNT_VALUE_ERROR = "GET_DISCOUNT_VALUE_ERROR";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_ERROR = "MAKE_PAYMENT_ERROR";
export const HANDLE_REGISTER_ERROR = "HANDLE_REGISTER_ERROR";
export const HANDLE_IS_USER_AUTHENTICATED = "HANDLE_IS_USER_AUTHENTICATED";
export const SET_USER_DATA = "SET_USER_DATA";
export const HANDLE_IS_VERIFICATION_CODE_SENT =
  "HANDLE_IS_VERIFICATION_CODE_SENT";
export const HANDLE_IS_AUTH_FETCHING = "HANDLE_IS_AUTH_FETCHING";
export const UPDATE_USER_RESPONSE = "UPDATE_USER_RESPONSE";
export const RESET_PASSWORD_RESPONSE = "RESET_PASSWORD_RESPONSE";
export const RESET_UPDATE_RESPONSE = "RESET_UPDATE_RESPONSE";
export const SET_ALL_USERS = "SET_ALL_USERS";
// Forgot Password
export const RECEIVE_PASSWORD_RESET_TOKEN = "RECEIVE_PASSWORD_RESET_TOKEN";
export const RECEIVE_PASSWORD_RESET_TOKEN_ERROR =
  "RECEIVE_PASSWORD_RESET_TOKEN_ERROR";
export const RESET_PASSWORD_TOKEN = "RESET_PASSWORD_TOKEN";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const FORGOT_PASSWORD_TOGGLE = "FORGOT_PASSWORD_TOGGLE";
// Verification
export const HANDLE_IS_USER_VERIFIED = "HANDLE_IS_USER_VERIFIED";

//Outlets
export const RECEIVE_USER_OUTLETS = "RECEIVE_USER_OUTLETS";
export const UPDATE_OUTLET = "UPDATE_OUTLET";
export const ADD_OUTLET = "ADD_OUTLET";
export const OUTLET_RESPONSE = "OUTLET_RESPONSE";
export const INIVTE_COLLAB_RESPONSE = "INIVTE_COLLAB_RESPONSE";
export const ADD_MENU_RESPONSE = "ADD_MENU_RESPONSE";
export const UPDATE_OUTLET_RESPONSE = "UPDATE_OUTLET_RESPONSE";

export const GET_SINGLE_OUTLET = "GET_SINGLE_OUTLET";
//Events
export const RECEIVE_USER_EVENTS = "RECEIVE_USER_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const GET_SINGLE_EVENT = "GET_SINGLE_EVENT";
export const UPDATE_EVENT_RESPONSE = "UPDATE_EVENT_RESPONSE";

export const TOMATI_DESKTOP_URL = "https://tomati-desktop.vercel.app/";
